### ISSUE TITLE
abs() missing

### ISSUE THREAD

**Issue by connellybarnes** [taschini/pyinterval#11]
Calling abs() on an interval currently does not result in the interval's absolute value:

    >>> abs(interval.interval[-1,1])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: bad operand type for abs(): 'interval'

However, this is easy to implement! This is a function I used:

    def interval_abs(i):
        """
        Get absolute value of interval i.
        """
        return (i | (-i)) & interval.interval[0, inf]

**Comment by taschini** [comment]
With the version currently in master it is now possible to take the absolute value of an interval:

```python
>>> abs(interval.interval[-1,1])
interval([0.0, 1.0])

```

**Comment by taschini** [comment]
Release 1.2.0 now adds support for the ``abs`` function.
