### ISSUE TITLE
Make it JSON serializable

### ISSUE THREAD

**Issue by yuxincs** [taschini/pyinterval#23]
It would be nice if the Interval class is JSON-serializable to store it to files/strings etc.

**Comment by barryam3** [comment]
It looks like it is.
```
>>> import interval
>>> import json
>>> json.dumps(interval.interval[1,2])
'[[1.0, 2.0]]'
```

**Comment by yuxincs** [comment]
> It looks like it is.
> 
> ```
> >>> import interval
> >>> import json
> >>> json.dumps(interval.interval[1,2])
> '[[1.0, 2.0]]'
> ```

Just tested it again and it seems like it is. I forgot why I opened this issue in the first place. 

Anyway, closing this issue now. Thanks for the reply :)
