### ISSUE TITLE
open vs closed intervals

### ISSUE THREAD

**Issue by akshatd** [taschini/pyinterval#6]
Hi!

Is there a way to specify if the interval is inclusive or exclusive of its endpoints? [] vs () ?

**Comment by taschini** [comment]
No. The topological and algebraic properties guaranteed by this library require that the intervals be closed.

**Comment by akshatd** [comment]
Thanks! If that functionality is needed, how would you suggest i go about it?

**Comment by taschini** [comment]
It very much depends on the purpose and hence what kind of properties you want to ensure. If you limit yourself to endpoints that can be represented without loss of precision in computer arithmetics (i.e., integers and rationals) I would probably keep an additional flag for each endpoint to store whether it is included in the interval.

If you need more general endpoints, i.e., if you want to model intervals with endpoints in the set of real numbers, soon or later you'll end up with either a set of guaranteed properties too weak to be useful or with “wrong” results, i.e., in situations where your results won't satisfy the properties that you initially set up to guarantee.
